import type { TurkishProvince } from "@/utils/turkish-provinces"

// Arapça arayüzde gösterilen il adları. rides.departure_city/arrival_city'ye
// yazılan ve aranan değer her zaman Türkçe kalır (bkz. turkish-provinces.ts,
// schemas.ts) — bu yalnızca AR locale'de görünen etiketi çevirir.
export const TURKISH_PROVINCE_NAMES_AR: Record<TurkishProvince, string> = {
  Adana: "أضنة",
  Adıyaman: "أديامان",
  Afyonkarahisar: "أفيون قره حصار",
  Ağrı: "أغرة",
  Amasya: "أماسيا",
  Ankara: "أنقرة",
  Antalya: "أنطاليا",
  Artvin: "أرتوين",
  Aydın: "أيدن",
  Balıkesir: "بالق أسير",
  Bilecik: "بيله جك",
  Bingöl: "بينكول",
  Bitlis: "بطليس",
  Bolu: "بولو",
  Burdur: "بوردور",
  Bursa: "بورصة",
  Çanakkale: "جنق قلعة",
  Çankırı: "جانقري",
  Çorum: "جوروم",
  Denizli: "دنيزلي",
  Diyarbakır: "ديار بكر",
  Edirne: "أدرنة",
  Elazığ: "معمورة العزيز",
  Erzincan: "أرزنجان",
  Erzurum: "أرضروم",
  Eskişehir: "أسكي شهر",
  Gaziantep: "غازي عنتاب",
  Giresun: "غيرسون",
  Gümüşhane: "كوموش خانة",
  Hakkari: "حكاري",
  Hatay: "حطاي",
  Isparta: "إسبرطة",
  Mersin: "مرسين",
  İstanbul: "إسطنبول",
  İzmir: "إزمير",
  Kars: "قارص",
  Kastamonu: "قسطموني",
  Kayseri: "قيصرية",
  Kırklareli: "كيركلاريلي",
  Kırşehir: "قرشهر",
  Kocaeli: "قوجه ايلي",
  Konya: "قونية",
  Kütahya: "كوتاهيا",
  Malatya: "ملاطية",
  Manisa: "مانيسا",
  Kahramanmaraş: "قهرمان مرعش",
  Mardin: "ماردين",
  Muğla: "موغلا",
  Muş: "موش",
  Nevşehir: "نوشهر",
  Niğde: "نيدة",
  Ordu: "أردو",
  Rize: "ريزا",
  Sakarya: "صقاريا",
  Samsun: "سامسون",
  Siirt: "سيرت",
  Sinop: "سينوب",
  Sivas: "سيواس",
  Tekirdağ: "تكيرداغ",
  Tokat: "توكات",
  Trabzon: "طرابزون",
  Tunceli: "تونجلي",
  Şanlıurfa: "أورفة",
  Uşak: "عشاق",
  Van: "وان",
  Yozgat: "يوزغات",
  Zonguldak: "زونغولداق",
  Aksaray: "أق سراي",
  Bayburt: "بايبورت",
  Karaman: "قرمان",
  Kırıkkale: "كريك قلعة",
  Batman: "باتمان",
  Şırnak: "شرناق",
  Bartın: "برتين",
  Ardahan: "أردهان",
  Iğdır: "إغدير",
  Yalova: "يالوفا",
  Karabük: "قره بوك",
  Kilis: "كيليس",
  Osmaniye: "عثمانية",
  Düzce: "دوزجه",
}

export function getProvinceDisplayName(city: string, locale: string): string {
  if (locale !== "ar") return city
  return TURKISH_PROVINCE_NAMES_AR[city as TurkishProvince] ?? city
}
